name: Test and Deploy
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint check
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        run: npm test
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: run build
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy
        run: echo "Deployed to prod"
