name: Test Project
on: 
    push:
        branches:
            - 'main'
    workflow_dispatch:
jobs: 
    test: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v5
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test

    
